package com.sigera.model;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActividadesExtracurricularesPorIncidencias generated by hbm2java
 */
@Entity
@Table(name = "ACTIVIDADES_EXTRACURRICULARES_POR_INCIDENCIAS"
)
public class ActividadesExtracurricularesPorIncidencias implements java.io.Serializable {

    private Integer idActividadPorIncidencia;
    private ActividadesExtracurriculares actividadesExtracurriculares;
    private Incidencias incidencias;

    public ActividadesExtracurricularesPorIncidencias() {
    }

   

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID_ACTIVIDAD_POR_INCIDENCIA", unique = true, nullable = false)
    public Integer getIdActividadPorIncidencia() {
        return this.idActividadPorIncidencia;
    }

    public void setIdActividadPorIncidencia(Integer idActividadPorIncidencia) {
        this.idActividadPorIncidencia = idActividadPorIncidencia;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_ACTIVIDADES_EXTRACURRICULARES", nullable = false)
    public ActividadesExtracurriculares getActividadesExtracurriculares() {
        return this.actividadesExtracurriculares;
    }

    public void setActividadesExtracurriculares(ActividadesExtracurriculares actividadesExtracurriculares) {
        this.actividadesExtracurriculares = actividadesExtracurriculares;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_INCIDENCIAS", nullable = false)
    public Incidencias getIncidencias() {
        return this.incidencias;
    }

    public void setIncidencias(Incidencias incidencias) {
        this.incidencias = incidencias;
    }

}
