package com.sigera.model;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActividadesExtracurriculares generated by hbm2java
 */
@Entity
@Table(name = "ACTIVIDADES_EXTRACURRICULARES"
)
public class ActividadesExtracurriculares implements java.io.Serializable {

    private Integer idActividadesExtracurriculares;
    private Profesor profesor;
    private String vcDireccion;
    private String vcReferencia;
    private int inNumeroContacto;
    private Date dtFechaInicio;
    private Date dtFechaRetorno;
    private Date dtFechaCreacion;
    private Date dtFechaModificacion;
    private Set<ActividadesExtracurricularesPorIncidencias> actividadesExtracurricularesPorIncidenciases = new HashSet(0);

    public ActividadesExtracurriculares() {
    }

   

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID_ACTIVIDADES_EXTRACURRICULARES", unique = true, nullable = false)
    public Integer getIdActividadesExtracurriculares() {
        return this.idActividadesExtracurriculares;
    }

    public void setIdActividadesExtracurriculares(Integer idActividadesExtracurriculares) {
        this.idActividadesExtracurriculares = idActividadesExtracurriculares;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_PROFESOR", nullable = false)
    public Profesor getProfesor() {
        return this.profesor;
    }

    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

    @Column(name = "VC_DIRECCION", nullable = false, length = 45)
    public String getVcDireccion() {
        return this.vcDireccion;
    }

    public void setVcDireccion(String vcDireccion) {
        this.vcDireccion = vcDireccion;
    }

    @Column(name = "VC_REFERENCIA", nullable = false, length = 45)
    public String getVcReferencia() {
        return this.vcReferencia;
    }

    public void setVcReferencia(String vcReferencia) {
        this.vcReferencia = vcReferencia;
    }

    @Column(name = "IN_NUMERO_CONTACTO", nullable = false)
    public int getInNumeroContacto() {
        return this.inNumeroContacto;
    }

    public void setInNumeroContacto(int inNumeroContacto) {
        this.inNumeroContacto = inNumeroContacto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_INICIO", nullable = false, length = 19)
    public Date getDtFechaInicio() {
        return this.dtFechaInicio;
    }

    public void setDtFechaInicio(Date dtFechaInicio) {
        this.dtFechaInicio = dtFechaInicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_RETORNO", nullable = false, length = 19)
    public Date getDtFechaRetorno() {
        return this.dtFechaRetorno;
    }

    public void setDtFechaRetorno(Date dtFechaRetorno) {
        this.dtFechaRetorno = dtFechaRetorno;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_CREACION", length = 19)
    public Date getDtFechaCreacion() {
        return this.dtFechaCreacion;
    }

    public void setDtFechaCreacion(Date dtFechaCreacion) {
        this.dtFechaCreacion = dtFechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_MODIFICACION", length = 19)
    public Date getDtFechaModificacion() {
        return this.dtFechaModificacion;
    }

    public void setDtFechaModificacion(Date dtFechaModificacion) {
        this.dtFechaModificacion = dtFechaModificacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "actividadesExtracurriculares")
    public Set<ActividadesExtracurricularesPorIncidencias> getActividadesExtracurricularesPorIncidenciases() {
        return this.actividadesExtracurricularesPorIncidenciases;
    }

    public void setActividadesExtracurricularesPorIncidenciases(Set<ActividadesExtracurricularesPorIncidencias> actividadesExtracurricularesPorIncidenciases) {
        this.actividadesExtracurricularesPorIncidenciases = actividadesExtracurricularesPorIncidenciases;
    }

}
