package com.sigera.model;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CursoPorProfesor generated by hbm2java
 */
@Entity
@Table(name = "CURSO_POR_PROFESOR"
)
public class CursoPorProfesor implements java.io.Serializable {

    private Integer idCursoPorProfesor;
    private Curso curso;
    private Horario horario;
    private Profesor profesor;
    private int idGrado;
    private int idSeccion;
    private int idAlumno;
    private Set<Asistencia> asistencias = new HashSet(0);
    private Set<Examen> examens = new HashSet(0);
    private Set<Tarea> tareas = new HashSet(0);

   
    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID_CURSO_POR_PROFESOR", unique = true, nullable = false)
    public Integer getIdCursoPorProfesor() {
        return this.idCursoPorProfesor;
    }

    public void setIdCursoPorProfesor(Integer idCursoPorProfesor) {
        this.idCursoPorProfesor = idCursoPorProfesor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_CURSO", nullable = false)
    public Curso getCurso() {
        return this.curso;
    }

    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_HORARIO", nullable = false)
    public Horario getHorario() {
        return this.horario;
    }

    public void setHorario(Horario horario) {
        this.horario = horario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_PROFESOR", nullable = false)
    public Profesor getProfesor() {
        return this.profesor;
    }

    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

    @Column(name = "ID_GRADO", nullable = false)
    public int getIdGrado() {
        return this.idGrado;
    }

    public void setIdGrado(int idGrado) {
        this.idGrado = idGrado;
    }

    @Column(name = "ID_SECCION", nullable = false)
    public int getIdSeccion() {
        return this.idSeccion;
    }

    public void setIdSeccion(int idSeccion) {
        this.idSeccion = idSeccion;
    }

    @Column(name = "ID_ALUMNO", nullable = false)
    public int getIdAlumno() {
        return this.idAlumno;
    }

    public void setIdAlumno(int idAlumno) {
        this.idAlumno = idAlumno;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cursoPorProfesor")
    public Set<Asistencia> getAsistencias() {
        return this.asistencias;
    }

    public void setAsistencias(Set<Asistencia> asistencias) {
        this.asistencias = asistencias;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cursoPorProfesor")
    public Set<Examen> getExamens() {
        return this.examens;
    }

    public void setExamens(Set<Examen> examens) {
        this.examens = examens;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cursoPorProfesor")
    public Set<Tarea> getTareas() {
        return this.tareas;
    }

    public void setTareas(Set<Tarea> tareas) {
        this.tareas = tareas;
    }

}
