package com.sigera.model;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name="DEPARTAMENTO"
    
)
public class Departamento  implements java.io.Serializable {


     private Integer idDepartamento;
     private String vcNombre;
     private Set<Provincia> provincias = new HashSet(0);

    public Departamento() {
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_DEPARTAMENTO", unique=true, nullable=false)
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

    
    @Column(name="VC_NOMBRE", nullable=false, length=45)
    public String getVcNombre() {
        return this.vcNombre;
    }
    
    public void setVcNombre(String vcNombre) {
        this.vcNombre = vcNombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departamento")
    public Set<Provincia> getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Set<Provincia> provincias) {
        this.provincias = provincias;
    }




}


