package com.sigera.model;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Distrito generated by hbm2java
 */
@Entity
@Table(name = "DISTRITO"
)
public class Distrito implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID_DISTRITO", unique = true, nullable = false)
    private Integer idDistrito;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_PROVINCIA", nullable = false)
    private Provincia provincia;
    @Column(name = "VC_NOMBRE", nullable = false, length = 45)
    private String vcNombre;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "distrito")
    private Set<Direccion> direccions = new HashSet(0);

    public Distrito() {
    }

    public Integer getIdDistrito() {
        return this.idDistrito;
    }

    public void setIdDistrito(Integer idDistrito) {
        this.idDistrito = idDistrito;
    }

    public Provincia getProvincia() {
        return this.provincia;
    }

    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }

    public String getVcNombre() {
        return this.vcNombre;
    }

    public void setVcNombre(String vcNombre) {
        this.vcNombre = vcNombre;
    }

    public Set getDireccions() {
        return this.direccions;
    }

    public void setDireccions(Set direccions) {
        this.direccions = direccions;
    }

}
