package com.sigera.model;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Examen generated by hbm2java
 */
@Entity
@Table(name = "EXAMEN"
)
public class Examen implements java.io.Serializable {

    private Integer idExamen;
    private CursoPorProfesor cursoPorProfesor;
    private TipoExamen tipoExamen;
    private int inNota;
    private Date dtFechaExamen;
    private String vcCreadoPor;
    private Date dtFechaCreacion;
    private String vcModificadoPor;
    private Date dtFechaModificacion;

    public Examen() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID_EXAMEN", unique = true, nullable = false)
    public Integer getIdExamen() {
        return this.idExamen;
    }

    public void setIdExamen(Integer idExamen) {
        this.idExamen = idExamen;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_CURSO_POR_PROFESOR", nullable = false)
    public CursoPorProfesor getCursoPorProfesor() {
        return this.cursoPorProfesor;
    }

    public void setCursoPorProfesor(CursoPorProfesor cursoPorProfesor) {
        this.cursoPorProfesor = cursoPorProfesor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_TIPO_EXAMEN", nullable = false)
    public TipoExamen getTipoExamen() {
        return this.tipoExamen;
    }

    public void setTipoExamen(TipoExamen tipoExamen) {
        this.tipoExamen = tipoExamen;
    }

    @Column(name = "IN_NOTA", nullable = false)
    public int getInNota() {
        return this.inNota;
    }

    public void setInNota(int inNota) {
        this.inNota = inNota;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_EXAMEN", nullable = false, length = 19)
    public Date getDtFechaExamen() {
        return this.dtFechaExamen;
    }

    public void setDtFechaExamen(Date dtFechaExamen) {
        this.dtFechaExamen = dtFechaExamen;
    }

    @Column(name = "VC_CREADO_POR", length = 45)
    public String getVcCreadoPor() {
        return this.vcCreadoPor;
    }

    public void setVcCreadoPor(String vcCreadoPor) {
        this.vcCreadoPor = vcCreadoPor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_CREACION", length = 19)
    public Date getDtFechaCreacion() {
        return this.dtFechaCreacion;
    }

    public void setDtFechaCreacion(Date dtFechaCreacion) {
        this.dtFechaCreacion = dtFechaCreacion;
    }

    @Column(name = "VC_MODIFICADO_POR", length = 45)
    public String getVcModificadoPor() {
        return this.vcModificadoPor;
    }

    public void setVcModificadoPor(String vcModificadoPor) {
        this.vcModificadoPor = vcModificadoPor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_MODIFICACION", length = 19)
    public Date getDtFechaModificacion() {
        return this.dtFechaModificacion;
    }

    public void setDtFechaModificacion(Date dtFechaModificacion) {
        this.dtFechaModificacion = dtFechaModificacion;
    }

}
