package com.sigera.model;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name = "HORARIO"
)
public class Horario implements java.io.Serializable {

    private Integer idHorario;
    private Salon salon;
    private Date dtDiaClases;
    private Date dtHoraInicio;
    private Date dtHoraFinal;
    private Set<CursoPorProfesor> cursoPorProfesors = new HashSet(0);

    public Horario() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID_HORARIO", unique = true, nullable = false)
    public Integer getIdHorario() {
        return this.idHorario;
    }

    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_SALON", nullable = false)
    public Salon getSalon() {
        return this.salon;
    }

    public void setSalon(Salon salon) {
        this.salon = salon;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_DIA_CLASES", nullable = false, length = 19)
    public Date getDtDiaClases() {
        return this.dtDiaClases;
    }

    public void setDtDiaClases(Date dtDiaClases) {
        this.dtDiaClases = dtDiaClases;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_HORA_INICIO", nullable = false, length = 19)
    public Date getDtHoraInicio() {
        return this.dtHoraInicio;
    }

    public void setDtHoraInicio(Date dtHoraInicio) {
        this.dtHoraInicio = dtHoraInicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_HORA_FINAL", nullable = false, length = 19)
    public Date getDtHoraFinal() {
        return this.dtHoraFinal;
    }

    public void setDtHoraFinal(Date dtHoraFinal) {
        this.dtHoraFinal = dtHoraFinal;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "horario")
    public Set<CursoPorProfesor> getCursoPorProfesors() {
        return this.cursoPorProfesors;
    }

    public void setCursoPorProfesors(Set<CursoPorProfesor> cursoPorProfesors) {
        this.cursoPorProfesors = cursoPorProfesors;
    }

}
