package com.sigera.model;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Incidencias generated by hbm2java
 */
@Entity
@Table(name = "INCIDENCIAS"
)
public class Incidencias implements java.io.Serializable {

    private Integer idIncidencias;
    private Alumno alumno;
    private Profesor profesor;
    private TipoIncidencia tipoIncidencia;
    private String vcDescripcion;
    private Date dtFechaIncidencia;
    private Date dtFechaRegistro;
    private Set<ActividadesExtracurricularesPorIncidencias> actividadesExtracurricularesPorIncidenciases = new HashSet(0);

    public Incidencias() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID_INCIDENCIAS", unique = true, nullable = false)
    public Integer getIdIncidencias() {
        return this.idIncidencias;
    }

    public void setIdIncidencias(Integer idIncidencias) {
        this.idIncidencias = idIncidencias;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_ALUMNO", nullable = false)
    public Alumno getAlumno() {
        return this.alumno;
    }

    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_PROFESOR", nullable = false)
    public Profesor getProfesor() {
        return this.profesor;
    }

    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_TIPO_INCIDENCIA", nullable = false)
    public TipoIncidencia getTipoIncidencia() {
        return this.tipoIncidencia;
    }

    public void setTipoIncidencia(TipoIncidencia tipoIncidencia) {
        this.tipoIncidencia = tipoIncidencia;
    }

    @Column(name = "VC_DESCRIPCION", nullable = false, length = 555)
    public String getVcDescripcion() {
        return this.vcDescripcion;
    }

    public void setVcDescripcion(String vcDescripcion) {
        this.vcDescripcion = vcDescripcion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_INCIDENCIA", nullable = false, length = 19)
    public Date getDtFechaIncidencia() {
        return this.dtFechaIncidencia;
    }

    public void setDtFechaIncidencia(Date dtFechaIncidencia) {
        this.dtFechaIncidencia = dtFechaIncidencia;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_REGISTRO", length = 19)
    public Date getDtFechaRegistro() {
        return this.dtFechaRegistro;
    }

    public void setDtFechaRegistro(Date dtFechaRegistro) {
        this.dtFechaRegistro = dtFechaRegistro;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "incidencias")
    public Set<ActividadesExtracurricularesPorIncidencias> getActividadesExtracurricularesPorIncidenciases() {
        return this.actividadesExtracurricularesPorIncidenciases;
    }

    public void setActividadesExtracurricularesPorIncidenciases(Set<ActividadesExtracurricularesPorIncidencias> actividadesExtracurricularesPorIncidenciases) {
        this.actividadesExtracurricularesPorIncidenciases = actividadesExtracurricularesPorIncidenciases;
    }

}
