package com.sigera.model;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Material generated by hbm2java
 */
@Entity
@Table(name = "MATERIAL"
)
public class Material implements java.io.Serializable {

    private Integer idMaterial;
    private ListaMateriales listaMateriales;
    private String vcNombre;
    private int inCantidad;

    public Material() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID_MATERIAL", unique = true, nullable = false)
    public Integer getIdMaterial() {
        return this.idMaterial;
    }

    public void setIdMaterial(Integer idMaterial) {
        this.idMaterial = idMaterial;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_LISTA_MATERIALES", nullable = false)
    public ListaMateriales getListaMateriales() {
        return this.listaMateriales;
    }

    public void setListaMateriales(ListaMateriales listaMateriales) {
        this.listaMateriales = listaMateriales;
    }

    @Column(name = "VC_NOMBRE", nullable = false, length = 45)
    public String getVcNombre() {
        return this.vcNombre;
    }

    public void setVcNombre(String vcNombre) {
        this.vcNombre = vcNombre;
    }

    @Column(name = "IN_CANTIDAD", nullable = false)
    public int getInCantidad() {
        return this.inCantidad;
    }

    public void setInCantidad(int inCantidad) {
        this.inCantidad = inCantidad;
    }

}
