package com.sigera.model;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Modulo generated by hbm2java
 */
@Entity
@Table(name = "MODULO"
)
public class Modulo implements java.io.Serializable {

    private Integer idModulo;
    private ModuloPadre moduloPadre;
    private String vcNombre;
    private boolean tyListar;
    private boolean tyCrear;
    private boolean tyActualizar;
    private boolean tyEliminar;
    private String vcCreadoPor;
    private Date dtFechaCreacion;
    private String vcModificadoPor;
    private Date dtFechaModificacion;
    private Set<Permiso> permisos = new HashSet(0);

    public Modulo() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID_MODULO", unique = true, nullable = false)
    public Integer getIdModulo() {
        return this.idModulo;
    }

    public void setIdModulo(Integer idModulo) {
        this.idModulo = idModulo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_MODULO_PADRE", nullable = false)
    public ModuloPadre getModuloPadre() {
        return this.moduloPadre;
    }

    public void setModuloPadre(ModuloPadre moduloPadre) {
        this.moduloPadre = moduloPadre;
    }

    @Column(name = "VC_NOMBRE", nullable = false, length = 45)
    public String getVcNombre() {
        return this.vcNombre;
    }

    public void setVcNombre(String vcNombre) {
        this.vcNombre = vcNombre;
    }

    @Column(name = "TY_LISTAR", nullable = false)
    public boolean isTyListar() {
        return this.tyListar;
    }

    public void setTyListar(boolean tyListar) {
        this.tyListar = tyListar;
    }

    @Column(name = "TY_CREAR", nullable = false)
    public boolean isTyCrear() {
        return this.tyCrear;
    }

    public void setTyCrear(boolean tyCrear) {
        this.tyCrear = tyCrear;
    }

    @Column(name = "TY_ACTUALIZAR", nullable = false)
    public boolean isTyActualizar() {
        return this.tyActualizar;
    }

    public void setTyActualizar(boolean tyActualizar) {
        this.tyActualizar = tyActualizar;
    }

    @Column(name = "TY_ELIMINAR", nullable = false)
    public boolean isTyEliminar() {
        return this.tyEliminar;
    }

    public void setTyEliminar(boolean tyEliminar) {
        this.tyEliminar = tyEliminar;
    }

    @Column(name = "VC_CREADO_POR", length = 45)
    public String getVcCreadoPor() {
        return this.vcCreadoPor;
    }

    public void setVcCreadoPor(String vcCreadoPor) {
        this.vcCreadoPor = vcCreadoPor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_CREACION", length = 19)
    public Date getDtFechaCreacion() {
        return this.dtFechaCreacion;
    }

    public void setDtFechaCreacion(Date dtFechaCreacion) {
        this.dtFechaCreacion = dtFechaCreacion;
    }

    @Column(name = "VC_MODIFICADO_POR", length = 45)
    public String getVcModificadoPor() {
        return this.vcModificadoPor;
    }

    public void setVcModificadoPor(String vcModificadoPor) {
        this.vcModificadoPor = vcModificadoPor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_MODIFICACION", length = 19)
    public Date getDtFechaModificacion() {
        return this.dtFechaModificacion;
    }

    public void setDtFechaModificacion(Date dtFechaModificacion) {
        this.dtFechaModificacion = dtFechaModificacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "modulo")
    public Set<Permiso> getPermisos() {
        return this.permisos;
    }

    public void setPermisos(Set<Permiso> permisos) {
        this.permisos = permisos;
    }

}
