package com.sigera.model;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModuloPadre generated by hbm2java
 */
@Entity
@Table(name = "MODULO_PADRE"
)
public class ModuloPadre implements java.io.Serializable {

    private Integer idModuloPadre;
    private String vcNombre;
    private Set<Modulo> modulos = new HashSet(0);

    public ModuloPadre() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID_MODULO_PADRE", unique = true, nullable = false)
    public Integer getIdModuloPadre() {
        return this.idModuloPadre;
    }

    public void setIdModuloPadre(Integer idModuloPadre) {
        this.idModuloPadre = idModuloPadre;
    }

    @Column(name = "VC_NOMBRE", nullable = false, length = 45)
    public String getVcNombre() {
        return this.vcNombre;
    }

    public void setVcNombre(String vcNombre) {
        this.vcNombre = vcNombre;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "moduloPadre")
    public Set<Modulo> getModulos() {
        return this.modulos;
    }

    public void setModulos(Set<Modulo> modulos) {
        this.modulos = modulos;
    }

}
