package com.sigera.model;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Permiso generated by hbm2java
 */
@Entity
@Table(name = "PERMISO"
)
public class Permiso implements java.io.Serializable {

    private Integer idPermiso;
    private Modulo modulo;
    private Perfil perfil;
    private boolean tyListar;
    private boolean tyCrear;
    private boolean tyActualizar;
    private boolean tyEliminar;

    public Permiso() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID_PERMISO", unique = true, nullable = false)
    public Integer getIdPermiso() {
        return this.idPermiso;
    }

    public void setIdPermiso(Integer idPermiso) {
        this.idPermiso = idPermiso;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_MODULO", nullable = false)
    public Modulo getModulo() {
        return this.modulo;
    }

    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_PERFIL", nullable = false)
    public Perfil getPerfil() {
        return this.perfil;
    }

    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }

    @Column(name = "TY_LISTAR", nullable = false)
    public boolean isTyListar() {
        return this.tyListar;
    }

    public void setTyListar(boolean tyListar) {
        this.tyListar = tyListar;
    }

    @Column(name = "TY_CREAR", nullable = false)
    public boolean isTyCrear() {
        return this.tyCrear;
    }

    public void setTyCrear(boolean tyCrear) {
        this.tyCrear = tyCrear;
    }

    @Column(name = "TY_ACTUALIZAR", nullable = false)
    public boolean isTyActualizar() {
        return this.tyActualizar;
    }

    public void setTyActualizar(boolean tyActualizar) {
        this.tyActualizar = tyActualizar;
    }

    @Column(name = "TY_ELIMINAR", nullable = false)
    public boolean isTyEliminar() {
        return this.tyEliminar;
    }

    public void setTyEliminar(boolean tyEliminar) {
        this.tyEliminar = tyEliminar;
    }

}
