package com.sigera.model;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "PERSONA"
)
public class Persona implements java.io.Serializable {

    private Integer idPersona;
    private Direccion direccion;
    private String vcNombre;
    private String vcApellidoPaterno;
    private String vcApellidoMaterno;
    private String inDni;
    private boolean tySexo;
    private String vcTelefono;
    private String vcCelular;
    private String vcEmail;
    private Date dtFechaNacimiento;
    private Date dtFechaRegistro;
    private Date dtFechaModificacion;
    private Set<Apoderado> apoderados = new HashSet(0);
    private Set<Profesor> profesors = new HashSet(0);
    private Set<Alumno> alumnos = new HashSet(0);
    private Set<Usuario> usuarios = new HashSet(0);

    public Persona() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID_PERSONA", unique = true, nullable = false)
    public Integer getIdPersona() {
        return this.idPersona;
    }

    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_DIRECCION", nullable = false)
    public Direccion getDireccion() {
        return this.direccion;
    }

    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }

    @Column(name = "VC_NOMBRE", nullable = false, length = 45)
    public String getVcNombre() {
        return this.vcNombre;
    }

    public void setVcNombre(String vcNombre) {
        this.vcNombre = vcNombre;
    }

    @Column(name = "VC_APELLIDO_PATERNO", nullable = false, length = 45)
    public String getVcApellidoPaterno() {
        return this.vcApellidoPaterno;
    }

    public void setVcApellidoPaterno(String vcApellidoPaterno) {
        this.vcApellidoPaterno = vcApellidoPaterno;
    }

    @Column(name = "VC_APELLIDO_MATERNO", nullable = false, length = 45)
    public String getVcApellidoMaterno() {
        return this.vcApellidoMaterno;
    }

    public void setVcApellidoMaterno(String vcApellidoMaterno) {
        this.vcApellidoMaterno = vcApellidoMaterno;
    }

    @Column(name = "IN_DNI", nullable = false, length = 45)
    public String getInDni() {
        return this.inDni;
    }

    public void setInDni(String inDni) {
        this.inDni = inDni;
    }

    @Column(name = "TY_SEXO", nullable = false)
    public boolean isTySexo() {
        return this.tySexo;
    }

    public void setTySexo(boolean tySexo) {
        this.tySexo = tySexo;
    }

    @Column(name = "VC_TELEFONO", nullable = false, length = 15)
    public String getVcTelefono() {
        return this.vcTelefono;
    }

    public void setVcTelefono(String vcTelefono) {
        this.vcTelefono = vcTelefono;
    }

    @Column(name = "VC_CELULAR", length = 45)
    public String getVcCelular() {
        return this.vcCelular;
    }

    public void setVcCelular(String vcCelular) {
        this.vcCelular = vcCelular;
    }

    @Column(name = "VC_EMAIL", nullable = false, length = 45)
    public String getVcEmail() {
        return this.vcEmail;
    }

    public void setVcEmail(String vcEmail) {
        this.vcEmail = vcEmail;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_NACIMIENTO", nullable = false, length = 19)
    public Date getDtFechaNacimiento() {
        return this.dtFechaNacimiento;
    }

    public void setDtFechaNacimiento(Date dtFechaNacimiento) {
        this.dtFechaNacimiento = dtFechaNacimiento;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_REGISTRO", length = 19)
    public Date getDtFechaRegistro() {
        return this.dtFechaRegistro;
    }

    public void setDtFechaRegistro(Date dtFechaRegistro) {
        this.dtFechaRegistro = dtFechaRegistro;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_MODIFICACION", length = 19)
    public Date getDtFechaModificacion() {
        return this.dtFechaModificacion;
    }

    public void setDtFechaModificacion(Date dtFechaModificacion) {
        this.dtFechaModificacion = dtFechaModificacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
    public Set<Apoderado> getApoderados() {
        return this.apoderados;
    }

    public void setApoderados(Set<Apoderado> apoderados) {
        this.apoderados = apoderados;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
    public Set<Profesor> getProfesors() {
        return this.profesors;
    }

    public void setProfesors(Set<Profesor> profesors) {
        this.profesors = profesors;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
    public Set<Alumno> getAlumnos() {
        return this.alumnos;
    }

    public void setAlumnos(Set<Alumno> alumnos) {
        this.alumnos = alumnos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

}
