package com.sigera.model;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name="PROVINCIA"
    
)
public class Provincia  implements java.io.Serializable {


     private Integer idProvincia;
     private Departamento departamento;
     private String vcNombre;
     private Set<Distrito> distritos = new HashSet(0);

    public Provincia() {
    }

	
   
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_PROVINCIA", unique=true, nullable=false)
    public Integer getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(Integer idProvincia) {
        this.idProvincia = idProvincia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_DEPARTAMENTO", nullable=false)
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="VC_NOMBRE", nullable=false, length=45)
    public String getVcNombre() {
        return this.vcNombre;
    }
    
    public void setVcNombre(String vcNombre) {
        this.vcNombre = vcNombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="provincia")
    public Set<Distrito> getDistritos() {
        return this.distritos;
    }
    
    public void setDistritos(Set<Distrito> distritos) {
        this.distritos = distritos;
    }




}


