package com.sigera.model;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoIncidencia generated by hbm2java
 */
@Entity
@Table(name = "TIPO_INCIDENCIA"
)
public class TipoIncidencia implements java.io.Serializable {

    private Integer idTipoIncidencia;
    private String vcNombre;
    private Set<Incidencias> incidenciases = new HashSet(0);

    public TipoIncidencia() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID_TIPO_INCIDENCIA", unique = true, nullable = false)
    public Integer getIdTipoIncidencia() {
        return this.idTipoIncidencia;
    }

    public void setIdTipoIncidencia(Integer idTipoIncidencia) {
        this.idTipoIncidencia = idTipoIncidencia;
    }

    @Column(name = "VC_NOMBRE", nullable = false, length = 100)
    public String getVcNombre() {
        return this.vcNombre;
    }

    public void setVcNombre(String vcNombre) {
        this.vcNombre = vcNombre;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoIncidencia")
    public Set<Incidencias> getIncidenciases() {
        return this.incidenciases;
    }

    public void setIncidenciases(Set<Incidencias> incidenciases) {
        this.incidenciases = incidenciases;
    }

}
