package com.sigera.model;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "USUARIO"
)
public class Usuario implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID_USUARIO", unique = true, nullable = false)
    private Integer idUsuario;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_ESTADO", nullable = false)
    private Estado estado;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_PERFIL", nullable = false)
    private Perfil perfil;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_PERSONA", nullable = false)
    private Persona persona;
    @Column(name = "VC_NICK", nullable = false, length = 45)
    private String vcNick;
    @Column(name = "VC_CLAVE", nullable = false, length = 45)
    private String vcClave;
    @Column(name = "VC_CREADO_POR", length = 45)
    private String vcCreadoPor;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_CREACION", length = 19)
    private Date dtFechaCreacion;
    @Column(name = "VC_MODIFICADO_POR", length = 45)
    private String vcModificadoPor;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_MODIFICADO_POR", length = 19)
    private Date dtModificadoPor;

    public Usuario() {
    }

    public Integer getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    public Estado getEstado() {
        return this.estado;
    }

    public void setEstado(Estado estado) {
        this.estado = estado;
    }

    public Perfil getPerfil() {
        return this.perfil;
    }

    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }

    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    public String getVcNick() {
        return this.vcNick;
    }

    public void setVcNick(String vcNick) {
        this.vcNick = vcNick;
    }

    public String getVcClave() {
        return this.vcClave;
    }

    public void setVcClave(String vcClave) {
        this.vcClave = vcClave;
    }

    public String getVcCreadoPor() {
        return this.vcCreadoPor;
    }

    public void setVcCreadoPor(String vcCreadoPor) {
        this.vcCreadoPor = vcCreadoPor;
    }

    public Date getDtFechaCreacion() {
        return this.dtFechaCreacion;
    }

    public void setDtFechaCreacion(Date dtFechaCreacion) {
        this.dtFechaCreacion = dtFechaCreacion;
    }

    public String getVcModificadoPor() {
        return this.vcModificadoPor;
    }

    public void setVcModificadoPor(String vcModificadoPor) {
        this.vcModificadoPor = vcModificadoPor;
    }

    public Date getDtModificadoPor() {
        return this.dtModificadoPor;
    }

    public void setDtModificadoPor(Date dtModificadoPor) {
        this.dtModificadoPor = dtModificadoPor;
    }

}
